import Navbar from "@/components/marketing/Navbar";
import { useEffect } from "react";

const Terms = () => {
  useEffect(() => {
    document.title = "Terms of Service - Socratica";
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }, []);

  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      
      <article className="container mx-auto px-6 py-16 max-w-4xl prose prose-slate dark:prose-invert">
        <h1>Terms of Service</h1>
        <p className="text-muted-foreground">Last updated: November 24, 2025</p>

        <h2>Agreement to Terms</h2>
        <p>
          By accessing or using Socratica, you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our service.
        </p>

        <h2>Description of Service</h2>
        <p>
          Socratica is an educational platform that provides AI-powered tutoring for students and analytics tools for teachers. The service includes course management, assignment tracking, and Socratic-style learning assistance.
        </p>

        <h2>User Accounts</h2>
        <h3>Account Creation</h3>
        <ul>
          <li>You must provide accurate and complete information when creating an account</li>
          <li>You are responsible for maintaining the confidentiality of your account credentials</li>
          <li>You must be at least 13 years old or have institutional authorization to use the service</li>
        </ul>

        <h3>User Responsibilities</h3>
        <p>You agree to:</p>
        <ul>
          <li>Use the service only for lawful educational purposes</li>
          <li>Not share your account with others</li>
          <li>Not attempt to circumvent security measures</li>
          <li>Respect intellectual property rights of others</li>
          <li>Not use the service to cheat or violate academic integrity policies</li>
        </ul>

        <h2>Acceptable Use</h2>
        <p>You may not:</p>
        <ul>
          <li>Use the service to harm, harass, or impersonate others</li>
          <li>Upload malicious code or attempt to gain unauthorized access</li>
          <li>Interfere with the proper functioning of the service</li>
          <li>Use automated systems to access the service without permission</li>
          <li>Resell or redistribute the service without authorization</li>
        </ul>

        <h2>Content and Intellectual Property</h2>
        <h3>Your Content</h3>
        <p>
          You retain ownership of content you upload to Socratica. By uploading content, you grant us a license to use, store, and process that content to provide our services.
        </p>

        <h3>Our Content</h3>
        <p>
          Socratica and its original content, features, and functionality are owned by us and are protected by intellectual property laws. You may not copy, modify, or distribute our content without permission.
        </p>

        <h2>AI-Generated Content</h2>
        <p>
          The AI tutoring responses are generated by artificial intelligence and should be used as educational guidance. We do not guarantee the accuracy or completeness of AI-generated content. Teachers and students should verify important information.
        </p>

        <h2>Subscription and Payment</h2>
        <ul>
          <li>Some features require a paid subscription</li>
          <li>Subscription fees are billed in advance on a monthly or annual basis</li>
          <li>You may cancel your subscription at any time</li>
          <li>Refunds are provided according to our refund policy</li>
        </ul>

        <h2>Data and Privacy</h2>
        <p>
          Your use of Socratica is also governed by our Privacy Policy. We collect and use data as described in that policy to provide and improve our services.
        </p>

        <h2>Service Availability</h2>
        <p>
          We strive to maintain service availability but do not guarantee uninterrupted access. We may modify, suspend, or discontinue features with or without notice.
        </p>

        <h2>Limitation of Liability</h2>
        <p>
          To the maximum extent permitted by law, Socratica shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use or inability to use the service.
        </p>

        <h2>Indemnification</h2>
        <p>
          You agree to indemnify and hold harmless Socratica from any claims, damages, or expenses arising from your use of the service or violation of these terms.
        </p>

        <h2>Termination</h2>
        <p>
          We may terminate or suspend your account immediately if you violate these terms. Upon termination, your right to use the service will immediately cease.
        </p>

        <h2>Changes to Terms</h2>
        <p>
          We reserve the right to modify these terms at any time. We will notify users of material changes. Continued use of the service after changes constitutes acceptance of the new terms.
        </p>

        <h2>Governing Law</h2>
        <p>
          These terms are governed by and construed in accordance with applicable laws, without regard to conflict of law principles.
        </p>

        <h2>Contact Information</h2>
        <p>
          For questions about these Terms of Service, contact us at:{" "}
          <a href="mailto:legal@socratica.app">legal@socratica.app</a>
        </p>
      </article>

      <footer className="border-t bg-muted/30 mt-20">
        <div className="container mx-auto px-6 py-8 text-center text-sm text-muted-foreground">
          <p>&copy; {new Date().getFullYear()} Socratica. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
};

export default Terms;
