import { useState } from "react";
import { Navigation } from "@/components/Navigation";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Checkbox } from "@/components/ui/checkbox";
import { Textarea } from "@/components/ui/textarea";
import { RadioGroup, RadioGroupItem } from "@/components/ui/radio-group";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { Loader2, Download, Copy } from "lucide-react";

interface ConsultingPlan {
  summary: string;
  assessmentChanges: string[];
  inClassActivities: string[];
  aiPolicy: string;
  lmsIntegration: string;
}

const Consulting = () => {
  const { toast } = useToast();
  const [step, setStep] = useState(1);
  const [loading, setLoading] = useState(false);
  const [plan, setPlan] = useState<ConsultingPlan | null>(null);
  
  const [formData, setFormData] = useState({
    courseTitle: "",
    discipline: "",
    classSize: "",
    delivery: "",
    currentAssessments: [] as string[],
    aiImpact: "",
    meetingFrequency: "",
    timeToGrade: "",
    comfortWithOral: "",
    lms: "",
    difficulty: "",
    goals: [] as string[],
  });

  const disciplines = [
    "Business",
    "Humanities",
    "Social Science",
    "Law/Policy",
    "STEM-light"
  ];

  const assessmentOptions = [
    "Midterm exam",
    "Final exam",
    "Weekly quizzes",
    "Discussion posts",
    "Group project",
    "Essay",
    "Presentation"
  ];

  const goalOptions = [
    "Keep academic integrity",
    "Increase participation",
    "More authentic tasks",
    "Faster prep"
  ];

  const canSubmit = () => {
    return formData.courseTitle && formData.discipline && formData.currentAssessments.length > 0;
  };

  const handleSubmit = async () => {
    if (!canSubmit()) {
      toast({
        title: "Missing information",
        description: "Please fill in course title, discipline, and at least one current assessment.",
        variant: "destructive",
      });
      return;
    }

    setLoading(true);
    try {
      const { data, error } = await supabase.functions.invoke('consulting-plan', {
        body: formData
      });

      if (error) throw error;

      setPlan(data);
      toast({
        title: "Plan generated!",
        description: "Your AI-resilient course restructuring plan is ready.",
      });
    } catch (error) {
      console.error('Error generating plan:', error);
      toast({
        title: "Error",
        description: "Failed to generate plan. Please try again.",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    if (!plan) return;
    
    const text = `
${plan.summary}

ASSESSMENT CHANGES:
${plan.assessmentChanges.map(item => `• ${item}`).join('\n')}

IN-CLASS ACTIVITIES:
${plan.inClassActivities.map(item => `• ${item}`).join('\n')}

AI POLICY:
${plan.aiPolicy}

LMS INTEGRATION:
${plan.lmsIntegration}
    `.trim();
    
    navigator.clipboard.writeText(text);
    toast({
      title: "Copied!",
      description: "Plan copied to clipboard.",
    });
  };

  const handleDownload = () => {
    if (!plan) return;
    
    const text = `
COURSE RESTRUCTURING PLAN
Generated by LiveQuiz

${plan.summary}

ASSESSMENT CHANGES:
${plan.assessmentChanges.map(item => `• ${item}`).join('\n')}

IN-CLASS ACTIVITIES:
${plan.inClassActivities.map(item => `• ${item}`).join('\n')}

AI POLICY:
${plan.aiPolicy}

LMS INTEGRATION:
${plan.lmsIntegration}
    `.trim();
    
    const blob = new Blob([text], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `course-plan-${formData.courseTitle.replace(/\s+/g, '-')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="min-h-screen flex flex-col">
      <Navigation />
      
      <main className="flex-1 py-12 px-4">
        <div className="container mx-auto max-w-7xl">
          <div className="mb-8">
            <h1 className="text-4xl font-bold mb-2">AI Consulting Dashboard</h1>
            <p className="text-muted-foreground">
              Answer a few questions about your course, and we'll generate a concrete plan to adapt to the AI era.
            </p>
          </div>

          <div className="grid lg:grid-cols-2 gap-8">
            {/* Form Section */}
            <div className="space-y-6">
              {step === 1 && (
                <Card>
                  <CardHeader>
                    <CardTitle>Step 1: Course Basics</CardTitle>
                    <CardDescription>Tell us about your course</CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <div>
                      <Label htmlFor="courseTitle">Course Title *</Label>
                      <Input
                        id="courseTitle"
                        value={formData.courseTitle}
                        onChange={(e) => setFormData({ ...formData, courseTitle: e.target.value })}
                        placeholder="e.g., Introduction to Business Strategy"
                      />
                    </div>

                    <div>
                      <Label htmlFor="discipline">Discipline *</Label>
                      <Select value={formData.discipline} onValueChange={(value) => setFormData({ ...formData, discipline: value })}>
                        <SelectTrigger>
                          <SelectValue placeholder="Select discipline" />
                        </SelectTrigger>
                        <SelectContent>
                          {disciplines.map((d) => (
                            <SelectItem key={d} value={d}>{d}</SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>

                    <div>
                      <Label htmlFor="classSize">Class Size</Label>
                      <Input
                        id="classSize"
                        type="number"
                        value={formData.classSize}
                        onChange={(e) => setFormData({ ...formData, classSize: e.target.value })}
                        placeholder="e.g., 30"
                      />
                    </div>

                    <div>
                      <Label htmlFor="delivery">Delivery Format</Label>
                      <Select value={formData.delivery} onValueChange={(value) => setFormData({ ...formData, delivery: value })}>
                        <SelectTrigger>
                          <SelectValue placeholder="Select format" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="in-person">In Person</SelectItem>
                          <SelectItem value="hybrid">Hybrid</SelectItem>
                          <SelectItem value="online">Online</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>

                    <Button onClick={() => setStep(2)} className="w-full">Next</Button>
                  </CardContent>
                </Card>
              )}

              {step === 2 && (
                <Card>
                  <CardHeader>
                    <CardTitle>Step 2: Current Assessments</CardTitle>
                    <CardDescription>What are you using now?</CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <div className="space-y-3">
                      <Label>Current Assessments *</Label>
                      {assessmentOptions.map((option) => (
                        <div key={option} className="flex items-center space-x-2">
                          <Checkbox
                            id={option}
                            checked={formData.currentAssessments.includes(option)}
                            onCheckedChange={(checked) => {
                              if (checked) {
                                setFormData({ ...formData, currentAssessments: [...formData.currentAssessments, option] });
                              } else {
                                setFormData({ ...formData, currentAssessments: formData.currentAssessments.filter(a => a !== option) });
                              }
                            }}
                          />
                          <Label htmlFor={option} className="font-normal cursor-pointer">{option}</Label>
                        </div>
                      ))}
                    </div>

                    <div>
                      <Label htmlFor="aiImpact">What part is getting hit by AI most?</Label>
                      <Textarea
                        id="aiImpact"
                        value={formData.aiImpact}
                        onChange={(e) => setFormData({ ...formData, aiImpact: e.target.value })}
                        placeholder="e.g., Students are using AI for essay assignments"
                        rows={3}
                      />
                    </div>

                    <div>
                      <Label htmlFor="meetingFrequency">How often do you meet?</Label>
                      <Select value={formData.meetingFrequency} onValueChange={(value) => setFormData({ ...formData, meetingFrequency: value })}>
                        <SelectTrigger>
                          <SelectValue placeholder="Select frequency" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="1x-week">Once per week</SelectItem>
                          <SelectItem value="2x-week">Twice per week</SelectItem>
                          <SelectItem value="3x-week">Three times per week</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>

                    <div className="flex gap-2">
                      <Button onClick={() => setStep(1)} variant="outline" className="w-full">Back</Button>
                      <Button onClick={() => setStep(3)} className="w-full">Next</Button>
                    </div>
                  </CardContent>
                </Card>
              )}

              {step === 3 && (
                <Card>
                  <CardHeader>
                    <CardTitle>Step 3: Constraints</CardTitle>
                    <CardDescription>Your teaching preferences</CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <div>
                      <Label>Time to grade</Label>
                      <RadioGroup value={formData.timeToGrade} onValueChange={(value) => setFormData({ ...formData, timeToGrade: value })}>
                        <div className="flex items-center space-x-2">
                          <RadioGroupItem value="low" id="low" />
                          <Label htmlFor="low" className="font-normal cursor-pointer">Low</Label>
                        </div>
                        <div className="flex items-center space-x-2">
                          <RadioGroupItem value="medium" id="medium" />
                          <Label htmlFor="medium" className="font-normal cursor-pointer">Medium</Label>
                        </div>
                        <div className="flex items-center space-x-2">
                          <RadioGroupItem value="high" id="high" />
                          <Label htmlFor="high" className="font-normal cursor-pointer">High</Label>
                        </div>
                      </RadioGroup>
                    </div>

                    <div>
                      <Label>Comfort with oral exams</Label>
                      <RadioGroup value={formData.comfortWithOral} onValueChange={(value) => setFormData({ ...formData, comfortWithOral: value })}>
                        <div className="flex items-center space-x-2">
                          <RadioGroupItem value="yes" id="oral-yes" />
                          <Label htmlFor="oral-yes" className="font-normal cursor-pointer">Yes</Label>
                        </div>
                        <div className="flex items-center space-x-2">
                          <RadioGroupItem value="no" id="oral-no" />
                          <Label htmlFor="oral-no" className="font-normal cursor-pointer">No</Label>
                        </div>
                      </RadioGroup>
                    </div>

                    <div>
                      <Label htmlFor="lms">LMS Used</Label>
                      <Select value={formData.lms} onValueChange={(value) => setFormData({ ...formData, lms: value })}>
                        <SelectTrigger>
                          <SelectValue placeholder="Select LMS" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="canvas">Canvas</SelectItem>
                          <SelectItem value="moodle">Moodle</SelectItem>
                          <SelectItem value="blackboard">Blackboard</SelectItem>
                          <SelectItem value="other">Other</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>

                    <div>
                      <Label>Desired difficulty</Label>
                      <RadioGroup value={formData.difficulty} onValueChange={(value) => setFormData({ ...formData, difficulty: value })}>
                        <div className="flex items-center space-x-2">
                          <RadioGroupItem value="low" id="diff-low" />
                          <Label htmlFor="diff-low" className="font-normal cursor-pointer">Low</Label>
                        </div>
                        <div className="flex items-center space-x-2">
                          <RadioGroupItem value="moderate" id="diff-moderate" />
                          <Label htmlFor="diff-moderate" className="font-normal cursor-pointer">Moderate</Label>
                        </div>
                        <div className="flex items-center space-x-2">
                          <RadioGroupItem value="rigorous" id="diff-rigorous" />
                          <Label htmlFor="diff-rigorous" className="font-normal cursor-pointer">Rigorous</Label>
                        </div>
                      </RadioGroup>
                    </div>

                    <div className="flex gap-2">
                      <Button onClick={() => setStep(2)} variant="outline" className="w-full">Back</Button>
                      <Button onClick={() => setStep(4)} className="w-full">Next</Button>
                    </div>
                  </CardContent>
                </Card>
              )}

              {step === 4 && (
                <Card>
                  <CardHeader>
                    <CardTitle>Step 4: Goals</CardTitle>
                    <CardDescription>What are your priorities?</CardDescription>
                  </CardHeader>
                  <CardContent className="space-y-4">
                    <div className="space-y-3">
                      <Label>Your Goals</Label>
                      {goalOptions.map((option) => (
                        <div key={option} className="flex items-center space-x-2">
                          <Checkbox
                            id={`goal-${option}`}
                            checked={formData.goals.includes(option)}
                            onCheckedChange={(checked) => {
                              if (checked) {
                                setFormData({ ...formData, goals: [...formData.goals, option] });
                              } else {
                                setFormData({ ...formData, goals: formData.goals.filter(g => g !== option) });
                              }
                            }}
                          />
                          <Label htmlFor={`goal-${option}`} className="font-normal cursor-pointer">{option}</Label>
                        </div>
                      ))}
                    </div>

                    <div className="flex gap-2">
                      <Button onClick={() => setStep(3)} variant="outline" className="w-full">Back</Button>
                      <Button onClick={handleSubmit} disabled={loading || !canSubmit()} className="w-full">
                        {loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                        Generate Plan
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              )}
            </div>

            {/* Results Section */}
            <div>
              <Card className="sticky top-20">
                <CardHeader>
                  <CardTitle>Recommended Structure</CardTitle>
                  <CardDescription>
                    {plan ? "Your AI-resilient course plan" : "Fill out the form to see your personalized plan"}
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  {loading ? (
                    <div className="flex items-center justify-center py-12">
                      <Loader2 className="h-8 w-8 animate-spin text-primary" />
                    </div>
                  ) : plan ? (
                    <div className="space-y-6">
                      <div>
                        <p className="text-sm font-medium text-muted-foreground mb-2">Summary</p>
                        <p className="text-sm">{plan.summary}</p>
                      </div>

                      <div>
                        <p className="text-sm font-medium text-muted-foreground mb-2">Assessment Changes</p>
                        <ul className="space-y-2">
                          {plan.assessmentChanges.map((change, i) => (
                            <li key={i} className="text-sm flex items-start gap-2">
                              <span className="text-primary mt-1">•</span>
                              <span>{change}</span>
                            </li>
                          ))}
                        </ul>
                      </div>

                      <div>
                        <p className="text-sm font-medium text-muted-foreground mb-2">In-Class Activities</p>
                        <ul className="space-y-2">
                          {plan.inClassActivities.map((activity, i) => (
                            <li key={i} className="text-sm flex items-start gap-2">
                              <span className="text-primary mt-1">•</span>
                              <span>{activity}</span>
                            </li>
                          ))}
                        </ul>
                      </div>

                      <div>
                        <p className="text-sm font-medium text-muted-foreground mb-2">Sample AI Policy</p>
                        <p className="text-sm bg-muted p-3 rounded-lg">{plan.aiPolicy}</p>
                      </div>

                      <div>
                        <p className="text-sm font-medium text-muted-foreground mb-2">LMS Integration</p>
                        <p className="text-sm">{plan.lmsIntegration}</p>
                      </div>

                      <div className="flex gap-2 pt-4">
                        <Button onClick={handleCopy} variant="outline" className="flex-1">
                          <Copy className="mr-2 h-4 w-4" />
                          Copy
                        </Button>
                        <Button onClick={handleDownload} variant="outline" className="flex-1">
                          <Download className="mr-2 h-4 w-4" />
                          Download
                        </Button>
                      </div>
                    </div>
                  ) : (
                    <div className="text-center py-12 text-muted-foreground">
                      <p className="text-sm">Your course restructuring plan will appear here</p>
                    </div>
                  )}
                </CardContent>
              </Card>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Consulting;
